blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/H3xWeMWjKQ
    about: Get help and chat with other PennyWise users
  - name: 📖 Documentation
    url: https://github.com/sarim2000/pennywiseai-tracker
    about: Check out the README for setup and usage instructions